SCROLL_PAUSE_TIME = 1
MAX_SCROLL_ATTEMPTS = 15
IMPLICIT_WAIT = 2
PAGE_LOAD_TIMEOUT = 10

CHROME_BINARY_PATH = '/opt/google/chrome/chrome'

# Performance settings
MAX_PLACES_PER_CITY = None  # No limit
EXTRACT_WAIT_TIME = 0.5
